spring:
  profiles:
    active: local
  aop:
    proxy-target-class: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        session_factory:
          interceptor: com.googlecode.hotire.springdatajpa.core.interceptor.CustomInterceptor
        ejb:
          interceptor: com.googlecode.hotire.springdatajpa.core.interceptor.CustomInterceptor
  datasource.hikari.maximum-pool-size: 1
logging:
  level:
    org:
      hibernate:
        engine:
          jdbc:
            spi.SqlExceptionHelper: OFF




---

spring:
  profiles: local
  jpa:
    hibernate:
    show-sql: true
    properties.hibernate.format_sql: true
    dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        metadata_builder_contributor: com.googlecode.hotire.springdatajpa.json.SqlFunctionsMetadataBuilderContributor


---

spring:
  profiles: beta
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa
    username: root
    password: 1234
  datasource.hikari.maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        metadata_builder_contributor: com.googlecode.hotire.springdatajpa.json.SqlFunctionsMetadataBuilderContributor
        use_sql_comments: true
        format_sql: true
        query:
          in_clause_parameter_padding: true
      org.hibernate.envers.store_data_at_delete: true
    show_sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true



