spring:
  jpa:
    hibernate:
    show-sql: true
    properties.hibernate.format_sql: true
    dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        metadata_builder_contributor: com.googlecode.hotire.springdatajpa.json.SqlFunctionsMetadataBuilderContributor